USE DATABASE GAMING_DB;
USE WAREHOUSE GAMING_ANALYTICS_WH;
USE SCHEMA RAW;

COPY INTO sessions
FROM @gaming_stage/sessions.csv
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

SELECT * FROM sessions LIMIT 10;
SELECT COUNT(*) FROM sessions;