USE DATABASE GAMING_DB;
USE WAREHOUSE GAMING_ANALYTICS_WH;
USE SCHEMA RAW;

COPY INTO raw.events
FROM @gaming_stage/events.csv
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);


SELECT * FROM raw.events LIMIT 10;
SELECT COUNT(*) FROM raw.events;
