USE DATABASE GAMING_DB;
USE WAREHOUSE GAMING_ANALYTICS_WH;


COPY INTO users
FROM @gaming_stage/users.csv
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

SELECT * FROM users LIMIT 10;
SELECT COUNT(*) FROM users;