USE DATABASE GAMING_DB;
USE WAREHOUSE GAMING_ANALYTICS_WH;
USE SCHEMA RAW;

COPY INTO purchases
FROM @gaming_stage/purchases.csv
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);


SELECT * FROM purchases LIMIT 10;
SELECT COUNT(*) FROM purchases;