USE DATABASE GAMING_DB;
USE WAREHOUSE GAMING_ANALYTICS_WH;


COPY INTO events
FROM @gaming_stage/events.csv
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);


SELECT * FROM events LIMIT 10;
SELECT COUNT(*) FROM events;
